<a href="https://colab.research.google.com/github/ThanhBinh2219/machine_learning/blob/main/Lab1_21130291_NguyenThanhBinh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#task 1.1
n = int(input("Nhập vào số phần tử của list:"))
lst = []
for i in range(1, n + 1):
  x = int(input("Nhập phần tử thứ " + str(i) + ":"))
  lst.append(x)

maxNum = max(lst)
minNum = min(lst)
totalNum = sum(lst)
asc = sorted(lst)

soDuong = 0
def timSoDuong(lst):
  global soDuong
  for i in lst:
    if i > 0:
      soDuong += 1
  return soDuong

soAm = 0
def timSoAm(lst):
  global soAm
  for i in lst:
    if i < 0:
      soAm += 1
  return soAm

print("Số lớn nhất trong list là: "  + str(maxNum))
print("Số nhỏ nhất trong list là: " + str(minNum))
print("Tổng phần tử có trong list là: " + str(totalNum))
print("Số dương có: " , timSoDuong(lst))
print("Số âm có: ", timSoAm(lst))
print("List đã sắp xếp: ", asc)


Nhập vào số phần tử của list:3
Nhập phần tử thứ 1:5
Nhập phần tử thứ 2:7
Nhập phần tử thứ 3:9
Số lớn nhất trong list là: 9
Số nhỏ nhất trong list là: 5
Tổng phần tử có trong list là:21
Số dương có:  3
Số âm có:  0
List đã sắp xếp:  [5, 7, 9]
5 7 9 

In [ ]:
#task 1.2
n = int(input("Nhập số nguyên n: "))
def tinhTongS(n):
  if (n == 1):
    return 1
  else:
    return n * tinhTongS(n - 1)

print(f"Tổng S: ", tinhTongS(n))

Nhập số nguyên n: 5
Tổng S:  120


In [3]:
#task 1.3
from  datetime import datetime
class Post:
    def __init__(self, content: str, subject: str, likes: int):
        self.__content = content
        self.__subject = subject
        self.__likes = likes

    def get_content(self):
        return self.__content

    def get_subject(self):
        return self.__subject

    def get_likes(self):
        return self.__likes


class Account:
    def __init__(self, name: str, email: str, country: str):
        self.__name = name
        self.__email = email
        self.__country = country
        self.__accounts = []
        self.__posts = []

    def get_name(self):
        return self.__name

    def get_email(self):
        return self.__email

    def get_country(self):
        return self.__country

    def get_accounts(self):
        return self.__accounts

    def get_post(self):
        return self.__posts

    def add_post(self, post):
        self.__posts.append(post)

    def add_account(self, account):
        self.__accounts.append(account)

    def get_max_like_post_by_friend(self):
        list_post_max_like = []
        for friend in self.get_accounts():
            max_likes_post = None
            max_likes = 0
            for post in friend.get_post():
                if post.get_likes() > max_likes:
                    max_likes = post.get_likes()
                    max_likes_post = post
            if max_likes_post:
                list_post_max_like.append((friend, max_likes_post))
        max_likes_friend = None
        max_likes_post = None
        max_likes = 0
        for friend, post in list_post_max_like:
            if post.get_likes() > max_likes:
                max_likes = post.get_likes()
                max_likes_friend = friend
                max_likes_post = post
        return max_likes_friend, max_likes_post


class AccountManager:
    def __init__(self):
        self.__accounts = []

    def get_accounts(self):
        return self.__accounts

    def add_account(self, account):
        self.__accounts.append(account)

    def group_accounts_by_post_like(self):
        result = {True: [], False: []}
        for account in self.get_accounts():
            if len(account.get_post()) < 5:
                result[False].append(account)
            else:
                result[True].append(account)
        return result

    def filter_accounts(self, country: str):
        filter_accounts = [account for account in self.__accounts if account.get_country() == country]
        filter_accounts.sort(key=lambda account: (-len(account.get_post()), account.get_name()))
        return filter_accounts

class VerifiedAccount(Account):
    def __init__(self, name: str, email: str, country: str, fromDate: datetime):
        super().__init__(name, email, country)
        self.__fromDate = fromDate

    def get_from_date(self):
        return self.__fromDate


class NormalAccount(Account):
    pass




# Tạo các đối tượng Post
post1 = Post("Cần ai đó đưa đi chơi", "8/3", 180)
post2 = Post("8/3, ai đó tặng hoa cho tôi đi", "8/3", 195)
post3 = Post("Không muốn đi học đâu, hihi", "Học hành", 209)
post4 = Post("Không muốn yêu thêm một ai nữa", "Tình cảm", 275)
post5 = Post("Anh chỉ là kẻ đến sau, tạm biệt em", "Tình cảm", 309)
post6 = Post("Xin lỗi vì những cuộc điện thoại", "Tình cảm", 3107)
post7 = Post("Cô đơn trong đêm", "Tình cảm", 72937)
post8 = Post("Yêu em", "Tình cảm", 763)

# Tạo các đối tượng Account và thêm bài đăng cho mỗi tài khoản
account1 = Account("Hoàng tử si tình", "hoanganh365@gmail.com", "Việt Nam")
account1.add_post(post1)
account1.add_post(post2)
account1.add_post(post3)
account1.add_post(post4)
account1.add_post(post5)

account2 = Account("Cô bé's ngốk", "cobengok_123@hotmail.com", "Việt Nam")
account2.add_post(post3)
account2.add_post(post4)

account3 = Account("Lãnh's Hàn's Thanh's Bình's", "lkqtg@hotmail.com", "Việt Nam")
account3.add_post(post5)
account3.add_post(post6)

# thêm tài khoản bạn bè
account1.add_account(account2)
account1.add_account(account3)
account3.add_account(account2)
account2.add_account(account1)

# Tạo đối tượng AccountManager và thêm tài khoản vào đó
account_manager = AccountManager()
account_manager.add_account(account1)
account_manager.add_account(account2)
account_manager.add_account(account3)

# Kiểm tra hàm get_max_like_post_by_friend
print("===============================================================")
print("Kiểm tra hàm get_max_like_post_by_friend")
max_likes_friend, max_likes_post = account1.get_max_like_post_by_friend()
print("Bài đăng có số lượt thích cao nhất của bạn bè là:", max_likes_post.get_content())
print("Người bạn có bài đăng đó là:", max_likes_friend.get_name())

# Kiểm tra hàm group_accounts_by_post_like
print("===============================================================")
print("Kiểm tra hàm group_accounts_by_post_like")
group_account = account_manager.group_accounts_by_post_like()
print("Số lượng tài khoản có ít bài đăng là:", len(group_account[False]))
print('Số lượng tài khoản có nhiều bài đăng là:', len(group_account[True]))
# kiểm tra hàm filter_accounts
print("===============================================================")
print("Kiểm tra hàm filter_accounts")
filtered_accounts = account_manager.filter_accounts("Việt Nam")
print("Danh sách các tài khoản từ Việt Nam, sắp xếp theo số lượng bài đăng giảm dần và tên tăng dần:")
for account in filtered_accounts:
    print(account.get_name(), ":", len(account.get_post()), "bài đăng")


Kiểm tra hàm get_max_like_post_by_friend
Bài đăng có số lượt thích cao nhất của bạn bè là: Xin lỗi vì những cuộc điện thoại
Người bạn có bài đăng đó là: Lãnh's Hàn's Thanh's Bình's
Kiểm tra hàm group_accounts_by_post_like
Số lượng tài khoản có ít bài đăng là: 2
Số lượng tài khoản có nhiều bài đăng là: 1
Kiểm tra hàm filter_accounts
Danh sách các tài khoản từ Việt Nam, sắp xếp theo số lượng bài đăng giảm dần và tên tăng dần:
Hoàng tử si tình : 5 bài đăng
Cô bé's ngốk : 2 bài đăng
Lãnh's Hàn's Thanh's Bình's : 2 bài đăng


# **TASK 2**

In [4]:
#task 2.1
import numpy as np

arr = np.arange(10, 26)
reverse_lst = list(reversed(arr))
print(reverse_lst)


[25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


In [7]:
#task 2.2
arr2 = np.array([1, 2, 3, 4])
print("Original array:", arr2)
repeat2 = np.tile(arr2, 2)
print("Repeating 2 times:", repeat2)
repeat3 = np.tile(arr2, 3)
print("Repeating 3 times:", repeat3)

Original array: [1 2 3 4]
Repeating 2 times: [1 2 3 4 1 2 3 4]
Repeating 3 times: [1 2 3 4 1 2 3 4 1 2 3 4]


In [8]:
#task 2.3
arr3 = np.array([[ 0.42, 0.48, 0.32],[ 0.74, 0.58, 0.38],[ 0.51, 0.34, 0.15 ]])
arr3[arr3 > 0.5] = 0.5
print(arr3)

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
